me=input("Enter your name: ").title()
Phone=input("Enter Your Phone Number: ")
job=input("Enter the job you want: ").title()
urfild=input("Enter your field or track about the job: " ).upper()
Employer_Name=input("What is Employer's Name? " ).capitalize()
Company=input("what is the Company Name? " ).upper()
print()
print("##"*50)
#                                                                   for IT HELP DESK MORE 
p1=f"Dear {Employer_Name}, \n  I hope this mail finds you well My name is {me} and I am writing this letter to express my interest in applying for the {job} job , as I believe that I possess everything necessary to execute the role and all associated duties while coming to you with a proactive approach and exceptional work ethic. \n First and foremost, I am the University of Matrouh graduate with a bachelor's degree in Information Technology & Computer Science  . At the university, I was among the top 2% of students with the best academic results and I attended the necessary training and tests to be a specialist in this field and the rest of the details and certificates are in my CV , I worked in student activism. This tremendous experience enabled me to become a great leader and helped me acquire exceptional analytical skills and the critical ability to work well both independently and in fast-paced group environments.  \n  In addition, I am a native Arabic speaker, fluent in English and  basic knowledge of French. After I practiced and trained as {job} in different places and Training, for over three years, I am proficient in using all the software required for this role. There, I spend most of my time providing technical support and assistance to the company's customers, solving any IT-related issues, and maintaining various hardware and software. Furthermore, I: \n  1. Train and supervise new employees and maintain the security and smoothness of the network and system. \n 2. Complete weekly reports and data and configure network devices.  \n  3. Carrying out various administrative tasks assigned by the supervisor. \n Finally, I would appreciate the opportunity to come in for an interview to discuss the position and my qualities in more detail in person. \n Thank you for your time and consideration and I look forward to hearing back from you soon. \n Kind regards, \n {me} \n Phone: {phone} "
print(p1)
